# Generated by Django 6.1.1 on 2026-09-07 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('numero_celular', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id_moto', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficinaMoto.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id_ordem', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('custo_pecas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_servico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_abertura', models.DateTimeField()),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('status_ordem', models.CharField(choices=[('em_andamento', 'Em andamento'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='em_andamento', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficinaMoto.cliente')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficinaMoto.moto')),
            ],
        ),
    ]
