# Generated by Django 6.1.1 on 2026-09-12 18:35

import oficinaMoto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficinaMoto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='codigo_acesso',
            field=models.CharField(default=oficinaMoto.models.gerar_codigo_acesso, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='custo_pecas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='custo_servico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='data_abertura',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
